### ISSUE TITLE
Real Test

### ISSUE THREAD

**Issue by AlexD10S** [al3mart/para-onboarding#24]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Test

### Parachain Name

Test

### ParaID

4286

### Parachain Manager Account

5CvkguduE5zDYCozyawTftRQPZqBR7wFfWuc2ZuzK4xSg48j

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

[para-2000-genesis-state.txt](https://github.com/al3mart/para-onboarding/files/12213356/para-2000-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[para-2000-wasm.txt](https://github.com/al3mart/para-onboarding/files/12213357/para-2000-wasm.txt)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Parachain is now being onboarded.
